### PR TITLE
Fix issue around "Class 'Grav\Plugin\Shortcodes\Shortcode' not found".

### LINKED ISSUE #4: Class 'Grav\Plugin\Shortcodes\Shortcode' not found
The plugin loads a class needing shortcode before shortcode plugin gets initialized:

https://github.com/Nebulius/grav-plugin-static-social-embeds/blob/master/static-social-embeds.php#L26-L27

### PR DESCRIPTION
**Pull request by funilrys**
This patch fixes Nebulius/grav-plugin-static-social-embeds#4.

Context:

    Before this patch (after 4.2.0 of shortcode-core), I could
    not run Grav (bin/grav and webserver) anymore.

    Indeed, I got "Class 'Grav\Plugin\Shortcodes\Shortcode' not found"
    as error and asked for help on the discord server of the
    Grav Core Team.

    @mahagr & @rhukster tried to help me with a patch+release
    (shortcode-core 4.2.1) but it still did not solve the issue.
    So I decided to fix it myself.

Resolution:

    I first followed the new structure by moving the shortcodes classes
    inside the `classes` directory.
    Same for `classes/SSEShortcode.php` which I moved to
    `classes/plugin/SSEShortcode.php`.

    In the `static-social-embeds.php` file, I just fixed the autoloader.
    In particularly the `getSubscribedEvents()` method. From now,
    `classes/plugin/SSEShortcode.php` is only loaded when we are not
    in the admin section.

    After, applying and testing those changes, onto my fresh development
    environment (latest grav-admin+docker-compose), everything worked
    back properly.

### CODE REVIEW

**Comment by funilrys** [comment]
@mahagr, fixed and tested.

**Comment by AmauryCarrade** [comment]
Thanks for the fix! I'll look into this this week-end :)

**Comment by mahagr** [comment]
Looks good to me on a quick look!

**Comment by funilrys** [comment]
ping @AmauryCarrade

**Comment by Fortyseven** [comment]
Just had this issue clobber my blog when I did an update. :(

**Comment by AmauryCarrade** [comment]
I totally forgot this issue and I'm sorry. Doing the QA now to check if everything is good, then I'll merge & publish.

**Review by AmauryCarrade — APPROVED** [review]
Okay, we're good

**Pull request merged**
